/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-10 16:53:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.contactmanager.model.Contact;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.contactmanager.model.Contact");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Contact contact = (Contact) request.getAttribute("contact");

    if (contact == null) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3 style=\"text-align:center;color:red;\">\r\n");
      out.write("    Contact not found\r\n");
      out.write("</h3>\r\n");
      out.write("\r\n");

    return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Edit Contact</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            margin:0;\r\n");
      out.write("            font-family:Arial;\r\n");
      out.write("            background:linear-gradient(to right,#4f46e5,#7c3aed);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar{\r\n");
      out.write("            background:#4f46e5;\r\n");
      out.write("            padding:15px;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container{\r\n");
      out.write("            height:90vh;\r\n");
      out.write("            display:flex;\r\n");
      out.write("            justify-content:center;\r\n");
      out.write("            align-items:center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card{\r\n");
      out.write("            width:400px;\r\n");
      out.write("            background:white;\r\n");
      out.write("            padding:30px;\r\n");
      out.write("            border-radius:12px;\r\n");
      out.write("            box-shadow:0 4px 20px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            padding:10px;\r\n");
      out.write("            margin-bottom:12px;\r\n");
      out.write("            border:1px solid #ccc;\r\n");
      out.write("            border-radius:6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            padding:12px;\r\n");
      out.write("            background:#4f46e5;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:6px;\r\n");
      out.write("            cursor:pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover{\r\n");
      out.write("            background:#3730a3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div>Contact Manager</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("        <h2 style=\"text-align:center;\">Edit Contact</h2>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"updateContact\" method=\"post\" onsubmit=\"return validateEdit()\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"email\"\r\n");
      out.write("                   value=\"");
      out.print( contact.getEmail() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" name=\"name\"\r\n");
      out.write("                   value=\"");
      out.print( contact.getName() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" id=\"phone\" name=\"phone\"\r\n");
      out.write("                   value=\"");
      out.print( contact.getPhone() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Update Contact</button>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function validateEdit() {\r\n");
      out.write("\r\n");
      out.write("    let phone = document.getElementById(\"phone\").value;\r\n");
      out.write("\r\n");
      out.write("    if (!/^[0-9]{10}$/.test(phone)) {\r\n");
      out.write("        alert(\"Phone must be exactly 10 digits!\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
